checks:
  - signal: "agenda"
    phrases:
      - "decides to include"

  - signal: "PGA"
    phrases:
      - "President of the General Assembly"

  - signal: "processes"
    phrases:
      - "co-facilitators"
      - "co-chairs"