patterns:
  - name: "General Assembly resolutions"
    template: "A/RES/{session}/{number}"
    session: 80
    start: 1

  - name: "General Assembly proposals"
    template: "A/{session}/L.{number}"
    session: 80
    start: 1

  - name: "C1 proposals"
    template: "A/C.{committee}/{session}/L.{number}"
    committee: 1
    session: 80
    start: 1

  - name: "C2 proposals"
    template: "A/C.{committee}/{session}/L.{number}"
    committee: 2
    session: 80
    start: 1

  - name: "C3 proposals"
    template: "A/C.{committee}/{session}/L.{number}"
    committee: 3
    session: 80
    start: 1

  - name: "C4 proposals"
    template: "A/C.{committee}/{session}/L.{number}"
    committee: 4
    session: 80
    start: 1

  - name: "C5 proposals"
    template: "A/C.{committee}/{session}/L.{number}"
    committee: 5
    session: 80
    start: 1

  - name: "C6 proposals"
    template: "A/C.{committee}/{session}/L.{number}"
    committee: 6
    session: 80
    start: 1
